### ISSUE TITLE
Vài lỗi giao diện

### ISSUE THREAD

**Issue by hoannc54** [colombo-trainee/LinhNT-bs001#5]
- Thiếu chuông thông báo ở góc bên phải trên.
- Dropdown menu hơi xấu, chưa đồng bộ với giao diện ngoài, tuy ko có trong thiết kế nhưng có làm thì nên để màu đồng bộ với bên ngoài, như background để màu trắng sữa thay cho đen .
- Phần chữ ở footer để màu đen mờ, chứ ko đen sáng như thiết kế.
- Nút search ấn vào sao hiện lên full màn hình vậy, chỉ là input nhỏ nhỏ hiện ra chứ.

**Comment by linhmuc** [comment]
cái chuông a bẩu ko cho vô
background dropdown em làm theo thiết kế mà
nút search em cũng làm vậy mà
